from .vectors import *
import pygame

COUR = 'cour.ttf'
COURBD = 'courbd.ttf'
ARIAL = 'arial.ttf'

# FONT_DIRECTORY = "C:\\Windows\\Fonts"
DEFAULT_FONT = COUR
DEFAULT_FONT_SIZE = 18

BLACK = Color(0,0,0)
RED = Color(255,0,0)
GREEN = Color(0,255,0)
BLUE = Color(0,0,255)
WHITE = Color(255,255,255)
MAGENTA = Color(255,0,255)
YELLOW = Color(255,255,0)
CYAN = Color(0,255,255)

_DEFAULT_AGENT_BODY_RADIUS = 64
_DEFAULT_AGENT_HEAD_RADIUS = 8
_DEFAULT_AGENT_BODY_COLOR = WHITE
_DEFAULT_AGENT_HEAD_COLOR = BLUE

DEFAULT_AGENT_IMAGE = pygame.Surface(P2Vector(2,2)*_DEFAULT_AGENT_BODY_RADIUS)

DEFAULT_AGENT_IMAGE.fill(MAGENTA)
DEFAULT_AGENT_IMAGE.set_colorkey(MAGENTA)
pygame.draw.circle(DEFAULT_AGENT_IMAGE, _DEFAULT_AGENT_BODY_COLOR, P2Vector(_DEFAULT_AGENT_BODY_RADIUS,_DEFAULT_AGENT_BODY_RADIUS), _DEFAULT_AGENT_BODY_RADIUS)
pygame.draw.circle(DEFAULT_AGENT_IMAGE, _DEFAULT_AGENT_HEAD_COLOR, P2Vector(_DEFAULT_AGENT_BODY_RADIUS*2-_DEFAULT_AGENT_HEAD_RADIUS,_DEFAULT_AGENT_BODY_RADIUS), _DEFAULT_AGENT_HEAD_RADIUS)
